services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - taxihub_mongo_data:/data/db

  driver-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver-service
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"

  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "8000:80"

volumes:
  taxihub_mongo_data:
