events {}

http {
    server {
        listen 80;

        location /drivers {
            proxy_pass http://driver-service:8080/drivers;
        }

        location /drivers/nearby {
            proxy_pass http://driver-service:8080/drivers/nearby;
        }

        location /health {
            proxy_pass http://driver-service:8080/health;
        }
    }
}
