events {}

http {
    server {
        listen 80;

        # Health
        location /health {
            proxy_pass http://driver-service:8080/health;
        }

        # Drivers API
        location /drivers {
            proxy_pass http://driver-service:8080/drivers;
        }

        location /drivers/nearby {
            proxy_pass http://driver-service:8080/drivers/nearby;
        }

        # Swagger
        location /swagger/ {
            proxy_pass http://driver-service:8080/swagger/;
        }
    }
}
