events {}

http {
   
    limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;
    limit_req_status 429;

    server {
        listen 80;

       
        location /health {
            proxy_pass http://driver-service:8080/health;
        }

       
        location /swagger/ {
            proxy_pass http://driver-service:8080/swagger/;
        }

       
        location /drivers {
           
            limit_req zone=perip burst=20 nodelay;

           
            if ($http_x_api_key != "taxihub-secret-key") {
                return 401;
            }

            proxy_pass http://driver-service:8080/drivers;
        }

        location /drivers/nearby {
            limit_req zone=perip burst=20 nodelay;

            if ($http_x_api_key != "taxihub-secret-key") {
                return 401;
            }

            proxy_pass http://driver-service:8080/drivers/nearby;
        }
    }
}
